//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.20 at 06:38:29 PM PST 
// Class content modified from generated version. 

package edu.sjsu.voidstar.project2.jaxb.tables;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import edu.sjsu.voidstar.project1.dao.City;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"city"})
@XmlRootElement(name = "Citys")
public class Citys implements EntityTable<City> {
    @XmlElement(name = "City")
    protected List<City> city = new ArrayList<>();
    
    public final void add(City city) {
		this.city.add(city);
	}
	
	public final void addAll(Collection<City> cities) {
		city.addAll(cities);	
	}
}
