//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.21 at 12:51:02 AM PST 
// Class content modified from generated version. 

package edu.sjsu.voidstar.project2.jaxb.tables;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import edu.sjsu.voidstar.project1.dao.CountryLanguage;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CountryLanguages", propOrder = { "countryLanguage" })
@XmlRootElement(name = "CountryLanguages")
public class CountryLanguages implements EntityTable<CountryLanguage> {
    @XmlElement(name = "CountryLanguage")
    protected List<CountryLanguage> countryLanguage = new ArrayList<>();
    
    public final void add(CountryLanguage countryLanguage) {
    	this.countryLanguage.add(countryLanguage);
	}
	
	public final void addAll(Collection<CountryLanguage> countryLanguages) {
		countryLanguage.addAll(countryLanguages);	
	}
	
	public List<CountryLanguage> getEntities() {
		return Collections.unmodifiableList(countryLanguage);
	}
}
