//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.21 at 12:51:07 AM PST 
// Class content modified from generated version.


package edu.sjsu.voidstar.project2.jaxb.tables;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import edu.sjsu.voidstar.project1.dao.Country;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "Countries")
@XmlType(name = "Countries", propOrder = { "country" })
public class Countries implements EntityTable<Country> {
    @XmlElement(name = "Country")
    protected List<Country> country = new ArrayList<>();
    
    public final void add(Country country) {
    	this.country.add(country);
	}
	
	public final void addAll(Collection<Country> countries) {
		country.addAll(countries);	
	}
	
	public List<Country> getEntities() {
		return Collections.unmodifiableList(country);
	}
}
