<definitions 
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
	xmlns:wsp="http://www.w3.org/ns/ws-policy" 
	xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" 
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:tns="http://ws.voidstar.sjsu.edu/soap/country"
	targetNamespace="http://ws.voidstar.sjsu.edu/soap/country"
	name="CountryPortService"
>	
	<types>
		<xs:schema>
			<xs:import namespace="http://ws.voidstar.sjsu.edu/soap/country" schemaLocation="../xsd/soap/CountryTypes.xsd" />
		</xs:schema>
	</types>
	
	<message name="getCountryByCode">
		<part name="parameters" element="tns:getCountryByCode"/>
	</message>
	
	<message name="getCountryByCodeResponse">
		<part name="parameters" element="tns:getCountryByCodeResponse"/>
	</message>

	<message name="getCountriesByContinent">
		<part name="parameters" element="tns:getCountriesByContinent"/>
	</message>
	
	<message name="getCountriesByContinentResponse">
		<part name="parameters" element="tns:getCountriesByContinentResponse"/>
	</message>

	<portType name="CountryService">
		<operation name="getCountryByCode">
			<input wsam:Action="http://ws.voidstar.sjsu.edu/CountryService/getCountryByCodeRequest" message="tns:getCountryByCode"/>
			<output wsam:Action="http://ws.voidstar.sjsu.edu/CountryService/getCountryByCodeResponse" message="tns:getCountryByCodeResponse"/>
		</operation>
		
		<operation name="getCountriesByContinent">
			<input wsam:Action="http://ws.voidstar.sjsu.edu/CountryService/getCountriesByContinentRequest" message="tns:getCountriesByContinent"/>
			<output wsam:Action="http://ws.voidstar.sjsu.edu/CountryService/getCountriesByContinentResponse" message="tns:getCountriesByContinentResponse"/>
		</operation>
	</portType>
	
	<binding name="CountryServicePortBinding" type="tns:CountryService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
		<operation name="getCountryByCode">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
		<operation name="getCountriesByContinent">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	
	<service name="CountryPortService">
		<port name="CountryServicePort" binding="tns:CountryServicePortBinding">
			<soap:address location="http://localhost:8123/country"/>
		</port>
	</service>
</definitions>
