
package edu.sjsu.voidstar.soap.city;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CityService", targetNamespace = "http://ws.voidstar.sjsu.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CityService {


    /**
     * 
     * @param cityId
     * @return
     *     returns edu.sjsu.voidstar.soap.city.City
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://ws.voidstar.sjsu.edu/")
    @RequestWrapper(localName = "getCityById", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.city.GetCityById")
    @ResponseWrapper(localName = "getCityByIdResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.city.GetCityByIdResponse")
    public City getCityById(
        @WebParam(name = "cityId", targetNamespace = "")
        Integer cityId);

    /**
     * 
     * @param cityName
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.soap.city.City>
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://ws.voidstar.sjsu.edu/")
    @RequestWrapper(localName = "getCityByName", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.city.GetCityByName")
    @ResponseWrapper(localName = "getCityByNameResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.city.GetCityByNameResponse")
    public List<City> getCityByName(
        @WebParam(name = "cityName", targetNamespace = "")
        String cityName);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.soap.city.City>
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://ws.voidstar.sjsu.edu/")
    @RequestWrapper(localName = "getCityByCountry", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.city.GetCityByCountry")
    @ResponseWrapper(localName = "getCityByCountryResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.city.GetCityByCountryResponse")
    public List<City> getCityByCountry(
        @WebParam(name = "country", targetNamespace = "")
        Country country);

}
