
package us.opulo.p.soap.countrylanguage;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import us.opulo.p.dao.Country;
import us.opulo.p.dao.CountryLanguage;
import us.opulo.p.dao.Language;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountryLanguageService", targetNamespace = "http://p.opulo.us/soap/countrylanguage")
@XmlSeeAlso({
    us.opulo.p.dao.ObjectFactory.class,
    us.opulo.p.soap.countrylanguage.ObjectFactory.class
})
public interface CountryLanguageService {


    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<us.opulo.p.dao.CountryLanguage>
     */
    @WebMethod
    @WebResult(name = "CountryLanguage", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCountryLanguagesByCountry", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesByCountry")
    @ResponseWrapper(localName = "getCountryLanguagesByCountryResponse", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesByCountryResponse")
    @Action(input = "http://p.opulo.us/CountryLanguageService/getCountryLanguagesByCodeRequest", output = "http://p.opulo.us/CountryLanguageService/getCountryLanguagesByCodeResponse")
    public List<CountryLanguage> getCountryLanguagesByCountry(
        @WebParam(name = "Country", targetNamespace = "http://p.opulo.us/dao")
        Country country);

    /**
     * 
     * @param language
     * @return
     *     returns java.util.List<us.opulo.p.dao.CountryLanguage>
     */
    @WebMethod
    @WebResult(name = "CountryLanguage", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCountryLanguagesByLanguage", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesByLanguage")
    @ResponseWrapper(localName = "getCountryLanguagesByLanguageResponse", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesByLanguageResponse")
    @Action(input = "http://p.opulo.us/CountryLanguageService/getCountryLanguagesByLanguageRequest", output = "http://p.opulo.us/CountryLanguageService/getCountryLanguagesByLanguageResponse")
    public List<CountryLanguage> getCountryLanguagesByLanguage(
        @WebParam(name = "Language", targetNamespace = "http://p.opulo.us/dao")
        Language language);

}
