
package us.opulo.p.soap.countrylanguage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CountryLanguagePortService", targetNamespace = "http://p.opulo.us/soap/countrylanguage", wsdlLocation = "http://localhost:8123/countrylanguage?wsdl")
public class CountryLanguagePortService
    extends Service
{

    private final static URL COUNTRYLANGUAGEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRYLANGUAGEPORTSERVICE_EXCEPTION;
    private final static QName COUNTRYLANGUAGEPORTSERVICE_QNAME = new QName("http://p.opulo.us/soap/countrylanguage", "CountryLanguagePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8123/countrylanguage?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRYLANGUAGEPORTSERVICE_WSDL_LOCATION = url;
        COUNTRYLANGUAGEPORTSERVICE_EXCEPTION = e;
    }

    public CountryLanguagePortService() {
        super(__getWsdlLocation(), COUNTRYLANGUAGEPORTSERVICE_QNAME);
    }

    public CountryLanguagePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYLANGUAGEPORTSERVICE_QNAME, features);
    }

    public CountryLanguagePortService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYLANGUAGEPORTSERVICE_QNAME);
    }

    public CountryLanguagePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYLANGUAGEPORTSERVICE_QNAME, features);
    }

    public CountryLanguagePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryLanguagePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountryLanguageService
     */
    @WebEndpoint(name = "CountryLanguageServicePort")
    public CountryLanguageService getCountryLanguageServicePort() {
        return super.getPort(new QName("http://p.opulo.us/soap/countrylanguage", "CountryLanguageServicePort"), CountryLanguageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryLanguageService
     */
    @WebEndpoint(name = "CountryLanguageServicePort")
    public CountryLanguageService getCountryLanguageServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://p.opulo.us/soap/countrylanguage", "CountryLanguageServicePort"), CountryLanguageService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYLANGUAGEPORTSERVICE_EXCEPTION!= null) {
            throw COUNTRYLANGUAGEPORTSERVICE_EXCEPTION;
        }
        return COUNTRYLANGUAGEPORTSERVICE_WSDL_LOCATION;
    }

}
