
package us.opulo.p.soap.countrylanguage;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import us.opulo.p.dao.Country;
import us.opulo.p.dao.CountryLanguage;
import us.opulo.p.dao.Language;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CountryLanguageService", targetNamespace = "http://p.opulo.us/soap/countrylanguage")
@XmlSeeAlso({
    us.opulo.p.soap.countrylanguage.ObjectFactory.class,
    us.opulo.p.dao.ObjectFactory.class
})
public interface CountryLanguageService {


    /**
     * 
     * @param language
     * @return
     *     returns java.util.List<us.opulo.p.dao.CountryLanguage>
     */
    @WebMethod
    @WebResult(name = "CountryLanguage", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCountryLanguagesForLanguage", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesForLanguage")
    @ResponseWrapper(localName = "getCountryLanguagesForLanguageResponse", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesForLanguageResponse")
    public List<CountryLanguage> getCountryLanguagesForLanguage(
        @WebParam(name = "Language", targetNamespace = "http://p.opulo.us/dao")
        Language language);

    /**
     * 
     * @param language
     * @return
     *     returns java.util.List<us.opulo.p.dao.CountryLanguage>
     */
    @WebMethod
    @WebResult(name = "CountryLanguage", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCountryLanguagesForLanguages", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesForLanguages")
    @ResponseWrapper(localName = "getCountryLanguagesForLanguagesResponse", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesForLanguagesResponse")
    public List<CountryLanguage> getCountryLanguagesForLanguages(
        @WebParam(name = "Language", targetNamespace = "http://p.opulo.us/dao")
        List<Language> language);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<us.opulo.p.dao.CountryLanguage>
     */
    @WebMethod
    @WebResult(name = "CountryLanguage", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCountryLanguagesForCountry", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesForCountry")
    @ResponseWrapper(localName = "getCountryLanguagesForCountryResponse", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesForCountryResponse")
    public List<CountryLanguage> getCountryLanguagesForCountry(
        @WebParam(name = "Country", targetNamespace = "http://p.opulo.us/dao")
        Country country);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<us.opulo.p.dao.CountryLanguage>
     */
    @WebMethod
    @WebResult(name = "CountryLanguage", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCountryLanguagesForCountries", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesForCountries")
    @ResponseWrapper(localName = "getCountryLanguagesForCountriesResponse", targetNamespace = "http://p.opulo.us/soap/countrylanguage", className = "us.opulo.p.soap.countrylanguage.GetCountryLanguagesForCountriesResponse")
    public List<CountryLanguage> getCountryLanguagesForCountries(
        @WebParam(name = "Country", targetNamespace = "http://p.opulo.us/dao")
        List<Country> country);

}
