
package us.opulo.p.soap.countrylanguage;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CountryLanguagePortService", targetNamespace = "http://p.opulo.us/soap/countrylanguage", wsdlLocation = "http://localhost:8123/countrylanguage?wsdl")
public class CountryLanguagePortService
    extends Service
{

    private final static URL COUNTRYLANGUAGEPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(us.opulo.p.soap.countrylanguage.CountryLanguagePortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = us.opulo.p.soap.countrylanguage.CountryLanguagePortService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8123/countrylanguage?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8123/countrylanguage?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COUNTRYLANGUAGEPORTSERVICE_WSDL_LOCATION = url;
    }

    public CountryLanguagePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryLanguagePortService() {
        super(COUNTRYLANGUAGEPORTSERVICE_WSDL_LOCATION, new QName("http://p.opulo.us/soap/countrylanguage", "CountryLanguagePortService"));
    }

    /**
     * 
     * @return
     *     returns CountryLanguageService
     */
    @WebEndpoint(name = "CountryLanguageServicePort")
    public CountryLanguageService getCountryLanguageServicePort() {
        return super.getPort(new QName("http://p.opulo.us/soap/countrylanguage", "CountryLanguageServicePort"), CountryLanguageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryLanguageService
     */
    @WebEndpoint(name = "CountryLanguageServicePort")
    public CountryLanguageService getCountryLanguageServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://p.opulo.us/soap/countrylanguage", "CountryLanguageServicePort"), CountryLanguageService.class, features);
    }

}
