
package edu.sjsu.voidstar.ws.mashup.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MashupService", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup/service")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MashupService {


    /**
     * 
     * @param countryCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMostSpokenLanguageInCountry", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup/service", className = "edu.sjsu.voidstar.ws.mashup.service.GetMostSpokenLanguageInCountry")
    @ResponseWrapper(localName = "getMostSpokenLanguageInCountryResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup/service", className = "edu.sjsu.voidstar.ws.mashup.service.GetMostSpokenLanguageInCountryResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/service/MashupService/getMostSpokenLanguageInCountryRequest", output = "http://ws.voidstar.sjsu.edu/mashup/service/MashupService/getMostSpokenLanguageInCountryResponse")
    public String getMostSpokenLanguageInCountry(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode);

}
