
package us.opulo.p.soap.infection;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import us.opulo.p.dao.City;
import us.opulo.p.dao.Country;
import us.opulo.p.dao.Infection;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InfectionService", targetNamespace = "http://p.opulo.us/soap/infection")
@XmlSeeAlso({
    us.opulo.p.dao.ObjectFactory.class,
    us.opulo.p.soap.infection.ObjectFactory.class
})
public interface InfectionService {


    /**
     * 
     * @param city
     * @return
     *     returns us.opulo.p.dao.Infection
     */
    @WebMethod
    @WebResult(name = "Infection", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getInfectionForCity", targetNamespace = "http://p.opulo.us/soap/infection", className = "us.opulo.p.soap.infection.GetInfectionForCity")
    @ResponseWrapper(localName = "getInfectionForCityResponse", targetNamespace = "http://p.opulo.us/soap/infection", className = "us.opulo.p.soap.infection.GetInfectionForCityResponse")
    @Action(input = "http://p.opulo.us/soap/infection/InfectionService/getInfectionForCityRequest", output = "http://p.opulo.us/soap/infection/InfectionService/getInfectionForCityResponse")
    public Infection getInfectionForCity(
        @WebParam(name = "City", targetNamespace = "http://p.opulo.us/dao")
        City city);

    /**
     * 
     * @return
     *     returns java.util.List<us.opulo.p.dao.Infection>
     */
    @WebMethod
    @WebResult(name = "Infection", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getAllInfections", targetNamespace = "http://p.opulo.us/soap/infection", className = "us.opulo.p.soap.infection.GetAllInfections")
    @ResponseWrapper(localName = "getAllInfectionsResponse", targetNamespace = "http://p.opulo.us/soap/infection", className = "us.opulo.p.soap.infection.GetAllInfectionsResponse")
    @Action(input = "http://p.opulo.us/soap/infection/InfectionService/getAllInfectionsRequest", output = "http://p.opulo.us/soap/infection/InfectionService/getAllInfectionsResponse")
    public List<Infection> getAllInfections();

    /**
     * 
     * @param city
     * @return
     *     returns java.util.List<us.opulo.p.dao.Infection>
     */
    @WebMethod
    @WebResult(name = "Infection", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getInfectionForCities", targetNamespace = "http://p.opulo.us/soap/infection", className = "us.opulo.p.soap.infection.GetInfectionForCities")
    @ResponseWrapper(localName = "getInfectionForCitiesResponse", targetNamespace = "http://p.opulo.us/soap/infection", className = "us.opulo.p.soap.infection.GetInfectionForCitiesResponse")
    @Action(input = "http://p.opulo.us/soap/infection/InfectionService/getInfectionForCitiesRequest", output = "http://p.opulo.us/soap/infection/InfectionService/getInfectionForCitiesResponse")
    public List<Infection> getInfectionForCities(
        @WebParam(name = "City", targetNamespace = "http://p.opulo.us/dao")
        List<City> city);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<us.opulo.p.dao.Infection>
     */
    @WebMethod
    @WebResult(name = "Infection", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getInfectionsForCountry", targetNamespace = "http://p.opulo.us/soap/infection", className = "us.opulo.p.soap.infection.GetInfectionsForCountry")
    @ResponseWrapper(localName = "getInfectionsForCountryResponse", targetNamespace = "http://p.opulo.us/soap/infection", className = "us.opulo.p.soap.infection.GetInfectionsForCountryResponse")
    @Action(input = "http://p.opulo.us/soap/infection/InfectionService/getInfectionsForCountryRequest", output = "http://p.opulo.us/soap/infection/InfectionService/getInfectionsForCountryResponse")
    public List<Infection> getInfectionsForCountry(
        @WebParam(name = "Country", targetNamespace = "http://p.opulo.us/dao")
        Country country);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<us.opulo.p.dao.Infection>
     */
    @WebMethod
    @WebResult(name = "Infection", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getInfectionsForCountries", targetNamespace = "http://p.opulo.us/soap/infection", className = "us.opulo.p.soap.infection.GetInfectionsForCountries")
    @ResponseWrapper(localName = "getInfectionsForCountriesResponse", targetNamespace = "http://p.opulo.us/soap/infection", className = "us.opulo.p.soap.infection.GetInfectionsForCountriesResponse")
    @Action(input = "http://p.opulo.us/soap/infection/InfectionService/getInfectionsForCountriesRequest", output = "http://p.opulo.us/soap/infection/InfectionService/getInfectionsForCountriesResponse")
    public List<Infection> getInfectionsForCountries(
        @WebParam(name = "Country", targetNamespace = "http://p.opulo.us/dao")
        List<Country> country);

}
