
package edu.sjsu.voidstar.soap.infection;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "InfectionService", targetNamespace = "http://ws.voidstar.sjsu.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InfectionService {


    /**
     * 
     * @param city
     * @return
     *     returns edu.sjsu.voidstar.soap.infection.Infection
     */
    @WebMethod
    @WebResult(name = "Infection", targetNamespace = "http://ws.voidstar.sjsu.edu/")
    @RequestWrapper(localName = "getInfectionByCity", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.infection.GetInfectionByCity")
    @ResponseWrapper(localName = "getInfectionByCityResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.infection.GetInfectionByCityResponse")
    public Infection getInfectionByCity(
        @WebParam(name = "City", targetNamespace = "http://ws.voidstar.sjsu.edu/")
        City city);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.soap.infection.Infection>
     */
    @WebMethod
    @WebResult(name = "Infections", targetNamespace = "http://ws.voidstar.sjsu.edu/")
    @RequestWrapper(localName = "getInfectionsForCountry", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.infection.GetInfectionsForCountry")
    @ResponseWrapper(localName = "getInfectionsForCountryResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.infection.GetInfectionsForCountryResponse")
    public List<Infection> getInfectionsForCountry(
        @WebParam(name = "Country", targetNamespace = "http://ws.voidstar.sjsu.edu/")
        Country country);

}
