
package edu.sjsu.voidstar.ws.soap.language;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LanguagePortService", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/language", wsdlLocation = "file:/C:/Users/shaun/git/voidstar/service/src/main/resources/wsdl/LanguageSoapService.wsdl")
public class LanguagePortService
    extends Service
{

    private final static URL LANGUAGEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException LANGUAGEPORTSERVICE_EXCEPTION;
    private final static QName LANGUAGEPORTSERVICE_QNAME = new QName("http://ws.voidstar.sjsu.edu/soap/language", "LanguagePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/shaun/git/voidstar/service/src/main/resources/wsdl/LanguageSoapService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LANGUAGEPORTSERVICE_WSDL_LOCATION = url;
        LANGUAGEPORTSERVICE_EXCEPTION = e;
    }

    public LanguagePortService() {
        super(__getWsdlLocation(), LANGUAGEPORTSERVICE_QNAME);
    }

    public LanguagePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LANGUAGEPORTSERVICE_QNAME, features);
    }

    public LanguagePortService(URL wsdlLocation) {
        super(wsdlLocation, LANGUAGEPORTSERVICE_QNAME);
    }

    public LanguagePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LANGUAGEPORTSERVICE_QNAME, features);
    }

    public LanguagePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LanguagePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LanguageService
     */
    @WebEndpoint(name = "LanguageServicePort")
    public LanguageService getLanguageServicePort() {
        return super.getPort(new QName("http://ws.voidstar.sjsu.edu/soap/language", "LanguageServicePort"), LanguageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LanguageService
     */
    @WebEndpoint(name = "LanguageServicePort")
    public LanguageService getLanguageServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.voidstar.sjsu.edu/soap/language", "LanguageServicePort"), LanguageService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LANGUAGEPORTSERVICE_EXCEPTION!= null) {
            throw LANGUAGEPORTSERVICE_EXCEPTION;
        }
        return LANGUAGEPORTSERVICE_WSDL_LOCATION;
    }

}
