
package edu.sjsu.voidstar.ws.soap.language;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import edu.sjsu.voidstar.ws.dao.City;
import edu.sjsu.voidstar.ws.dao.Country;
import edu.sjsu.voidstar.ws.dao.Language;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LanguageService", targetNamespace = "http://p.opulo.us/soap/language")
@XmlSeeAlso({
    edu.sjsu.voidstar.ws.dao.ObjectFactory.class,
    edu.sjsu.voidstar.ws.soap.language.ObjectFactory.class
})
public interface LanguageService {


    /**
     * 
     * @param id
     * @return
     *     returns edu.sjsu.voidstar.ws.dao.Language
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getLanguageById", targetNamespace = "http://p.opulo.us/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguageById")
    @ResponseWrapper(localName = "getLanguageByIdResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguageByIdResponse")
    @Action(input = "http://p.opulo.us/LanguageService/getLanguageByIdRequest", output = "http://p.opulo.us/LanguageService/getLanguageByIdResponse")
    public Language getLanguageById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param name
     * @return
     *     returns edu.sjsu.voidstar.ws.dao.Language
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getLanguageByName", targetNamespace = "http://p.opulo.us/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguageByName")
    @ResponseWrapper(localName = "getLanguageByNameResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguageByNameResponse")
    @Action(input = "http://p.opulo.us/LanguageService/getLanguageByNameRequest", output = "http://p.opulo.us/LanguageService/getLanguageByNameResponse")
    public Language getLanguageByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.ws.dao.Language>
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getLanguagesByCountry", targetNamespace = "http://p.opulo.us/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguagesByCountry")
    @ResponseWrapper(localName = "getLanguagesByCountryResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguagesByCountryResponse")
    @Action(input = "http://p.opulo.us/LanguageService/getLanguagesByCountryRequest", output = "http://p.opulo.us/LanguageService/getLanguagesByCountryResponse")
    public List<Language> getLanguagesByCountry(
        @WebParam(name = "Country", targetNamespace = "http://p.opulo.us/dao")
        Country country);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.ws.dao.Language>
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getSortedLanguagesByCountry", targetNamespace = "http://p.opulo.us/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetSortedLanguagesByCountry")
    @ResponseWrapper(localName = "getSortedLanguagesByCountryResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetSortedLanguagesByCountryResponse")
    @Action(input = "http://p.opulo.us/LanguageService/getSortedLanguagesByCountryRequest", output = "http://p.opulo.us/LanguageService/getSortedLanguagesByCountryResponse")
    public List<Language> getSortedLanguagesByCountry(
        @WebParam(name = "Country", targetNamespace = "http://p.opulo.us/dao")
        Country country);

    /**
     * 
     * @param city
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.ws.dao.Language>
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getLanguagesByCity", targetNamespace = "http://p.opulo.us/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguagesByCity")
    @ResponseWrapper(localName = "getLanguagesByCityResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguagesByCityResponse")
    @Action(input = "http://p.opulo.us/LanguageService/getLanguagesByCityRequest", output = "http://p.opulo.us/LanguageService/getLanguagesByCityResponse")
    public List<Language> getLanguagesByCity(
        @WebParam(name = "City", targetNamespace = "http://p.opulo.us/dao")
        City city);

}
