
package edu.sjsu.voidstar.ws.soap.country;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import edu.sjsu.voidstar.ws.dao.Country;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountryService", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/country")
@XmlSeeAlso({
    edu.sjsu.voidstar.ws.dao.ObjectFactory.class,
    edu.sjsu.voidstar.ws.soap.country.ObjectFactory.class
})
public interface CountryService {


    /**
     * 
     * @param countryCode
     * @return
     *     returns edu.sjsu.voidstar.ws.dao.Country
     */
    @WebMethod
    @WebResult(name = "Country", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
    @RequestWrapper(localName = "getCountryByCode", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/country", className = "edu.sjsu.voidstar.ws.soap.country.GetCountryByCode")
    @ResponseWrapper(localName = "getCountryByCodeResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/country", className = "edu.sjsu.voidstar.ws.soap.country.GetCountryByCodeResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/CountryService/getCountryByCodeRequest", output = "http://ws.voidstar.sjsu.edu/CountryService/getCountryByCodeResponse")
    public Country getCountryByCode(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode);

    /**
     * 
     * @param continent
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.ws.dao.Country>
     */
    @WebMethod
    @WebResult(name = "Country", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
    @RequestWrapper(localName = "getCountryByContinent", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/country", className = "edu.sjsu.voidstar.ws.soap.country.GetCountryByContinent")
    @ResponseWrapper(localName = "getCountryByContinentResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/country", className = "edu.sjsu.voidstar.ws.soap.country.GetCountryByContinentResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/CountryService/getCountryByContinentRequest", output = "http://ws.voidstar.sjsu.edu/CountryService/getCountryByContinentResponse")
    public List<Country> getCountryByContinent(
        @WebParam(name = "continent", targetNamespace = "")
        String continent);

}
