
package us.opulo.p.mashup;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MashupService", targetNamespace = "http://p.opulo.us/mashup")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MashupService {


    /**
     * 
     * @param countryCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLanguagesSpokenInCountry", targetNamespace = "http://p.opulo.us/mashup", className = "us.opulo.p.mashup.GetLanguagesSpokenInCountry")
    @ResponseWrapper(localName = "getLanguagesSpokenInCountryResponse", targetNamespace = "http://p.opulo.us/mashup", className = "us.opulo.p.mashup.GetLanguagesSpokenInCountryResponse")
    public String getLanguagesSpokenInCountry(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode);

    /**
     * 
     * @param cityName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNumberOfZombiesInCity", targetNamespace = "http://p.opulo.us/mashup", className = "us.opulo.p.mashup.GetNumberOfZombiesInCity")
    @ResponseWrapper(localName = "getNumberOfZombiesInCityResponse", targetNamespace = "http://p.opulo.us/mashup", className = "us.opulo.p.mashup.GetNumberOfZombiesInCityResponse")
    public String getNumberOfZombiesInCity(
        @WebParam(name = "cityName", targetNamespace = "")
        String cityName);

    /**
     * 
     * @param languageName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountriesWhichSpeakLanguage", targetNamespace = "http://p.opulo.us/mashup", className = "us.opulo.p.mashup.GetCountriesWhichSpeakLanguage")
    @ResponseWrapper(localName = "getCountriesWhichSpeakLanguageResponse", targetNamespace = "http://p.opulo.us/mashup", className = "us.opulo.p.mashup.GetCountriesWhichSpeakLanguageResponse")
    public String getCountriesWhichSpeakLanguage(
        @WebParam(name = "languageName", targetNamespace = "")
        String languageName);

}
