
package edu.sjsu.voidstar.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CityService", targetNamespace = "http://ws.voidstar.sjsu.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CityService {


    /**
     * 
     * @param arg0
     * @return
     *     returns edu.sjsu.voidstar.ws.City
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCityById", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.ws.GetCityById")
    @ResponseWrapper(localName = "getCityByIdResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.ws.GetCityByIdResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/CityService/getCityByIdRequest", output = "http://ws.voidstar.sjsu.edu/CityService/getCityByIdResponse")
    public City getCityById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
