
package edu.sjsu.voidstar.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CityServiceService", targetNamespace = "http://ws.voidstar.sjsu.edu/", wsdlLocation = "http://localhost:8123/city?wsdl")
public class CityServiceService
    extends Service
{

    private final static URL CITYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CITYSERVICESERVICE_EXCEPTION;
    private final static QName CITYSERVICESERVICE_QNAME = new QName("http://ws.voidstar.sjsu.edu/", "CityServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8123/city?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CITYSERVICESERVICE_WSDL_LOCATION = url;
        CITYSERVICESERVICE_EXCEPTION = e;
    }

    public CityServiceService() {
        super(__getWsdlLocation(), CITYSERVICESERVICE_QNAME);
    }

    public CityServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CITYSERVICESERVICE_QNAME, features);
    }

    public CityServiceService(URL wsdlLocation) {
        super(wsdlLocation, CITYSERVICESERVICE_QNAME);
    }

    public CityServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CITYSERVICESERVICE_QNAME, features);
    }

    public CityServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CityServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CityService
     */
    @WebEndpoint(name = "CityServicePort")
    public CityService getCityServicePort() {
        return super.getPort(new QName("http://ws.voidstar.sjsu.edu/", "CityServicePort"), CityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CityService
     */
    @WebEndpoint(name = "CityServicePort")
    public CityService getCityServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.voidstar.sjsu.edu/", "CityServicePort"), CityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CITYSERVICESERVICE_EXCEPTION!= null) {
            throw CITYSERVICESERVICE_EXCEPTION;
        }
        return CITYSERVICESERVICE_WSDL_LOCATION;
    }

}
