
package edu.sjsu.voidstar.soap.country;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CountryService", targetNamespace = "http://ws.voidstar.sjsu.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountryService {


    /**
     * 
     * @param countryCode
     * @return
     *     returns edu.sjsu.voidstar.soap.country.Country
     */
    @WebMethod
    @WebResult(name = "Country", targetNamespace = "http://ws.voidstar.sjsu.edu/")
    @RequestWrapper(localName = "getCountryByCode", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.country.GetCountryByCode")
    @ResponseWrapper(localName = "getCountryByCodeResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.country.GetCountryByCodeResponse")
    public Country getCountryByCode(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode);

    /**
     * 
     * @param continent
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.soap.country.Country>
     */
    @WebMethod
    @WebResult(name = "Countries", targetNamespace = "http://ws.voidstar.sjsu.edu/")
    @RequestWrapper(localName = "getCountryByContinent", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.country.GetCountryByContinent")
    @ResponseWrapper(localName = "getCountryByContinentResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.soap.country.GetCountryByContinentResponse")
    public List<Country> getCountryByContinent(
        @WebParam(name = "continent", targetNamespace = "")
        String continent);

}
