
package us.opulo.p.soap.country;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import us.opulo.p.dao.Country;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CountryService", targetNamespace = "http://p.opulo.us/soap/country")
@XmlSeeAlso({
    us.opulo.p.soap.country.ObjectFactory.class,
    us.opulo.p.dao.ObjectFactory.class
})
public interface CountryService {


    /**
     * 
     * @return
     *     returns java.util.List<us.opulo.p.dao.Country>
     */
    @WebMethod
    @WebResult(name = "Country", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getAllCountries", targetNamespace = "http://p.opulo.us/soap/country", className = "us.opulo.p.soap.country.GetAllCountries")
    @ResponseWrapper(localName = "getAllCountriesResponse", targetNamespace = "http://p.opulo.us/soap/country", className = "us.opulo.p.soap.country.GetAllCountriesResponse")
    public List<Country> getAllCountries();

    /**
     * 
     * @param code
     * @return
     *     returns us.opulo.p.dao.Country
     */
    @WebMethod
    @WebResult(name = "Country", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCountryWithCode", targetNamespace = "http://p.opulo.us/soap/country", className = "us.opulo.p.soap.country.GetCountryWithCode")
    @ResponseWrapper(localName = "getCountryWithCodeResponse", targetNamespace = "http://p.opulo.us/soap/country", className = "us.opulo.p.soap.country.GetCountryWithCodeResponse")
    public Country getCountryWithCode(
        @WebParam(name = "code", targetNamespace = "")
        String code);

    /**
     * 
     * @param countryCodes
     * @return
     *     returns java.util.List<us.opulo.p.dao.Country>
     */
    @WebMethod
    @WebResult(name = "Country", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCountriesWithCodes", targetNamespace = "http://p.opulo.us/soap/country", className = "us.opulo.p.soap.country.GetCountriesWithCodes")
    @ResponseWrapper(localName = "getCountriesWithCodesResponse", targetNamespace = "http://p.opulo.us/soap/country", className = "us.opulo.p.soap.country.GetCountriesWithCodesResponse")
    public List<Country> getCountriesWithCodes(
        @WebParam(name = "countryCodes", targetNamespace = "")
        List<String> countryCodes);

    /**
     * 
     * @param continent
     * @return
     *     returns java.util.List<us.opulo.p.dao.Country>
     */
    @WebMethod
    @WebResult(name = "Country", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCountriesOnContinent", targetNamespace = "http://p.opulo.us/soap/country", className = "us.opulo.p.soap.country.GetCountriesOnContinent")
    @ResponseWrapper(localName = "getCountriesOnContinentResponse", targetNamespace = "http://p.opulo.us/soap/country", className = "us.opulo.p.soap.country.GetCountriesOnContinentResponse")
    public List<Country> getCountriesOnContinent(
        @WebParam(name = "continent", targetNamespace = "")
        String continent);

    /**
     * 
     * @param continents
     * @return
     *     returns java.util.List<us.opulo.p.dao.Country>
     */
    @WebMethod
    @WebResult(name = "Country", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCountriesOnContinents", targetNamespace = "http://p.opulo.us/soap/country", className = "us.opulo.p.soap.country.GetCountriesOnContinents")
    @ResponseWrapper(localName = "getCountriesOnContinentsResponse", targetNamespace = "http://p.opulo.us/soap/country", className = "us.opulo.p.soap.country.GetCountriesOnContinentsResponse")
    public List<Country> getCountriesOnContinents(
        @WebParam(name = "continents", targetNamespace = "")
        List<String> continents);

}
