
package us.opulo.p.soap.country;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CountryPortService", targetNamespace = "http://p.opulo.us/soap/country", wsdlLocation = "http://localhost:8123/country?wsdl")
public class CountryPortService
    extends Service
{

    private final static URL COUNTRYPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRYPORTSERVICE_EXCEPTION;
    private final static QName COUNTRYPORTSERVICE_QNAME = new QName("http://p.opulo.us/soap/country", "CountryPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8123/country?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRYPORTSERVICE_WSDL_LOCATION = url;
        COUNTRYPORTSERVICE_EXCEPTION = e;
    }

    public CountryPortService() {
        super(__getWsdlLocation(), COUNTRYPORTSERVICE_QNAME);
    }

    public CountryPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYPORTSERVICE_QNAME, features);
    }

    public CountryPortService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYPORTSERVICE_QNAME);
    }

    public CountryPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYPORTSERVICE_QNAME, features);
    }

    public CountryPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountryService
     */
    @WebEndpoint(name = "CountryServicePort")
    public CountryService getCountryServicePort() {
        return super.getPort(new QName("http://p.opulo.us/soap/country", "CountryServicePort"), CountryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryService
     */
    @WebEndpoint(name = "CountryServicePort")
    public CountryService getCountryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://p.opulo.us/soap/country", "CountryServicePort"), CountryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYPORTSERVICE_EXCEPTION!= null) {
            throw COUNTRYPORTSERVICE_EXCEPTION;
        }
        return COUNTRYPORTSERVICE_WSDL_LOCATION;
    }

}
