
package edu.sjsu.voidstar.ws.city;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CityService", targetNamespace = "http://ws.voidstar.sjsu.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CityService {


    /**
     * 
     * @param cityId
     * @return
     *     returns edu.sjsu.voidstar.ws.city.City
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://ws.voidstar.sjsu.edu/")
    @RequestWrapper(localName = "getCityById", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.ws.city.GetCityById")
    @ResponseWrapper(localName = "getCityByIdResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.ws.city.GetCityByIdResponse")
    public City getCityById(
        @WebParam(name = "cityId", targetNamespace = "")
        Integer cityId);

    /**
     * 
     * @param cityName
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.ws.city.City>
     */
    @WebMethod
    @WebResult(name = "Cities", targetNamespace = "")
    @RequestWrapper(localName = "getCitiesByName", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.ws.city.GetCitiesByName")
    @ResponseWrapper(localName = "getCitiesByNameResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.ws.city.GetCitiesByNameResponse")
    public List<City> getCitiesByName(
        @WebParam(name = "cityName", targetNamespace = "")
        String cityName);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.ws.city.City>
     */
    @WebMethod
    @WebResult(name = "Cities", targetNamespace = "")
    @RequestWrapper(localName = "getCitiesByCountry", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.ws.city.GetCitiesByCountry")
    @ResponseWrapper(localName = "getCitiesByCountryResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/", className = "edu.sjsu.voidstar.ws.city.GetCitiesByCountryResponse")
    public List<City> getCitiesByCountry(
        @WebParam(name = "country", targetNamespace = "")
        Country country);

}
