
package us.opulo.p.soap.city;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import us.opulo.p.dao.City;
import us.opulo.p.dao.Country;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CityService", targetNamespace = "http://p.opulo.us/soap/city")
@XmlSeeAlso({
    us.opulo.p.dao.ObjectFactory.class,
    us.opulo.p.soap.city.ObjectFactory.class
})
public interface CityService {


    /**
     * 
     * @return
     *     returns java.util.List<us.opulo.p.dao.City>
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getAllCities", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetAllCities")
    @ResponseWrapper(localName = "getAllCitiesResponse", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetAllCitiesResponse")
    public List<City> getAllCities();

    /**
     * 
     * @param id
     * @return
     *     returns us.opulo.p.dao.City
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCityWithId", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCityWithId")
    @ResponseWrapper(localName = "getCityWithIdResponse", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCityWithIdResponse")
    public City getCityWithId(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param ids
     * @return
     *     returns java.util.List<us.opulo.p.dao.City>
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCitiesWithIds", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCitiesWithIds")
    @ResponseWrapper(localName = "getCitiesWithIdsResponse", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCitiesWithIdsResponse")
    public List<City> getCitiesWithIds(
        @WebParam(name = "ids", targetNamespace = "")
        List<Integer> ids);

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<us.opulo.p.dao.City>
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCitiesWithName", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCitiesWithName")
    @ResponseWrapper(localName = "getCitiesWithNameResponse", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCitiesWithNameResponse")
    public List<City> getCitiesWithName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param names
     * @return
     *     returns java.util.List<us.opulo.p.dao.City>
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCitiesWithNames", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCitiesWithNames")
    @ResponseWrapper(localName = "getCitiesWithNamesResponse", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCitiesWithNamesResponse")
    public List<City> getCitiesWithNames(
        @WebParam(name = "names", targetNamespace = "")
        List<String> names);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<us.opulo.p.dao.City>
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCitiesInCountry", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCitiesInCountry")
    @ResponseWrapper(localName = "getCitiesInCountryResponse", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCitiesInCountryResponse")
    public List<City> getCitiesInCountry(
        @WebParam(name = "Country", targetNamespace = "http://p.opulo.us/dao")
        Country country);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<us.opulo.p.dao.City>
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getCitiesInCountries", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCitiesInCountries")
    @ResponseWrapper(localName = "getCitiesInCountriesResponse", targetNamespace = "http://p.opulo.us/soap/city", className = "us.opulo.p.soap.city.GetCitiesInCountriesResponse")
    public List<City> getCitiesInCountries(
        @WebParam(name = "Country", targetNamespace = "http://p.opulo.us/dao")
        List<Country> country);

}
