
package us.opulo.p.soap.city;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CityPortService", targetNamespace = "http://p.opulo.us/soap/city", wsdlLocation = "http://localhost:8123/city?wsdl")
public class CityPortService
    extends Service
{

    private final static URL CITYPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CITYPORTSERVICE_EXCEPTION;
    private final static QName CITYPORTSERVICE_QNAME = new QName("http://p.opulo.us/soap/city", "CityPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8123/city?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CITYPORTSERVICE_WSDL_LOCATION = url;
        CITYPORTSERVICE_EXCEPTION = e;
    }

    public CityPortService() {
        super(__getWsdlLocation(), CITYPORTSERVICE_QNAME);
    }

    public CityPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CITYPORTSERVICE_QNAME, features);
    }

    public CityPortService(URL wsdlLocation) {
        super(wsdlLocation, CITYPORTSERVICE_QNAME);
    }

    public CityPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CITYPORTSERVICE_QNAME, features);
    }

    public CityPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CityPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CityService
     */
    @WebEndpoint(name = "CityServicePort")
    public CityService getCityServicePort() {
        return super.getPort(new QName("http://p.opulo.us/soap/city", "CityServicePort"), CityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CityService
     */
    @WebEndpoint(name = "CityServicePort")
    public CityService getCityServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://p.opulo.us/soap/city", "CityServicePort"), CityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CITYPORTSERVICE_EXCEPTION!= null) {
            throw CITYPORTSERVICE_EXCEPTION;
        }
        return CITYPORTSERVICE_WSDL_LOCATION;
    }

}
