
package edu.sjsu.voidstar.ws.soap.city;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CityPortService", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/city", wsdlLocation = "file:/C:/cygwin/home/jcampos/dev/voidstar/service/src/main/resources/wsdl/CitySoapService.wsdl")
public class CityPortService
    extends Service
{

    private final static URL CITYPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.sjsu.voidstar.ws.soap.city.CityPortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.sjsu.voidstar.ws.soap.city.CityPortService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/cygwin/home/jcampos/dev/voidstar/service/src/main/resources/wsdl/CitySoapService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/cygwin/home/jcampos/dev/voidstar/service/src/main/resources/wsdl/CitySoapService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CITYPORTSERVICE_WSDL_LOCATION = url;
    }

    public CityPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CityPortService() {
        super(CITYPORTSERVICE_WSDL_LOCATION, new QName("http://ws.voidstar.sjsu.edu/soap/city", "CityPortService"));
    }

    /**
     * 
     * @return
     *     returns CityService
     */
    @WebEndpoint(name = "CityServicePort")
    public CityService getCityServicePort() {
        return super.getPort(new QName("http://ws.voidstar.sjsu.edu/soap/city", "CityServicePort"), CityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CityService
     */
    @WebEndpoint(name = "CityServicePort")
    public CityService getCityServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.voidstar.sjsu.edu/soap/city", "CityServicePort"), CityService.class, features);
    }

}
