
package edu.sjsu.voidstar.ws.soap.language;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import edu.sjsu.voidstar.ws.dao.City;
import edu.sjsu.voidstar.ws.dao.Country;
import edu.sjsu.voidstar.ws.dao.Language;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LanguageService", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/language")
@XmlSeeAlso({
    edu.sjsu.voidstar.ws.dao.ObjectFactory.class,
    edu.sjsu.voidstar.ws.soap.language.ObjectFactory.class
})
public interface LanguageService {


    /**
     * 
     * @param id
     * @return
     *     returns edu.sjsu.voidstar.ws.dao.Language
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
    @RequestWrapper(localName = "getLanguageById", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguageById")
    @ResponseWrapper(localName = "getLanguageByIdResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguageByIdResponse")
    public Language getLanguageById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param language
     * @return
     *     returns edu.sjsu.voidstar.ws.dao.Language
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
    @RequestWrapper(localName = "getLanguageByName", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguageByName")
    @ResponseWrapper(localName = "getLanguageByNameResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguageByNameResponse")
    public Language getLanguageByName(
        @WebParam(name = "language", targetNamespace = "")
        String language);

    /**
     * 
     * @param city
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.ws.dao.Language>
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
    @RequestWrapper(localName = "getLanguagesByCity", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguagesByCity")
    @ResponseWrapper(localName = "getLanguagesByCityResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguagesByCityResponse")
    public List<Language> getLanguagesByCity(
        @WebParam(name = "City", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
        City city);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.ws.dao.Language>
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
    @RequestWrapper(localName = "getLanguagesByCountry", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguagesByCountry")
    @ResponseWrapper(localName = "getLanguagesByCountryResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/language", className = "edu.sjsu.voidstar.ws.soap.language.GetLanguagesByCountryResponse")
    public List<Language> getLanguagesByCountry(
        @WebParam(name = "Country", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
        Country country);

}
