
package edu.sjsu.voidstar.ws.soap.language;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LanguagePortService", targetNamespace = "http://p.opulo.us/soap/language", wsdlLocation = "file:/home/jason/Dropbox/Jason/Dev/Workspaces/School/CS157B/voidstar/voidstar/service/src/main/resources/wsdl/LanguageSoapService.wsdl")
public class LanguagePortService
    extends Service
{

    private final static URL LANGUAGEPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.sjsu.voidstar.ws.soap.language.LanguagePortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.sjsu.voidstar.ws.soap.language.LanguagePortService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/jason/Dropbox/Jason/Dev/Workspaces/School/CS157B/voidstar/voidstar/service/src/main/resources/wsdl/LanguageSoapService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/jason/Dropbox/Jason/Dev/Workspaces/School/CS157B/voidstar/voidstar/service/src/main/resources/wsdl/LanguageSoapService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LANGUAGEPORTSERVICE_WSDL_LOCATION = url;
    }

    public LanguagePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LanguagePortService() {
        super(LANGUAGEPORTSERVICE_WSDL_LOCATION, new QName("http://p.opulo.us/soap/language", "LanguagePortService"));
    }

    /**
     * 
     * @return
     *     returns LanguageService
     */
    @WebEndpoint(name = "LanguageServicePort")
    public LanguageService getLanguageServicePort() {
        return super.getPort(new QName("http://p.opulo.us/soap/language", "LanguageServicePort"), LanguageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LanguageService
     */
    @WebEndpoint(name = "LanguageServicePort")
    public LanguageService getLanguageServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://p.opulo.us/soap/language", "LanguageServicePort"), LanguageService.class, features);
    }

}
