
package edu.sjsu.voidstar.ws.soap.city;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import edu.sjsu.voidstar.ws.dao.City;
import edu.sjsu.voidstar.ws.dao.Country;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CityService", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/city")
@XmlSeeAlso({
    edu.sjsu.voidstar.ws.dao.ObjectFactory.class,
    edu.sjsu.voidstar.ws.soap.city.ObjectFactory.class
})
public interface CityService {


    /**
     * 
     * @param cityId
     * @return
     *     returns edu.sjsu.voidstar.ws.dao.City
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
    @RequestWrapper(localName = "getCityById", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/city", className = "edu.sjsu.voidstar.ws.soap.city.GetCityById")
    @ResponseWrapper(localName = "getCityByIdResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/city", className = "edu.sjsu.voidstar.ws.soap.city.GetCityByIdResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/CityService/getCityByIdRequest", output = "http://ws.voidstar.sjsu.edu/CityService/getCityByIdResponse")
    public City getCityById(
        @WebParam(name = "cityId", targetNamespace = "")
        Integer cityId);

    /**
     * 
     * @param cityName
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.ws.dao.City>
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
    @RequestWrapper(localName = "getCityByName", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/city", className = "edu.sjsu.voidstar.ws.soap.city.GetCityByName")
    @ResponseWrapper(localName = "getCityByNameResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/city", className = "edu.sjsu.voidstar.ws.soap.city.GetCityByNameResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/CityService/getCityByNameRequest", output = "http://ws.voidstar.sjsu.edu/CityService/getCityByNameResponse")
    public List<City> getCityByName(
        @WebParam(name = "cityName", targetNamespace = "")
        String cityName);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<edu.sjsu.voidstar.ws.dao.City>
     */
    @WebMethod
    @WebResult(name = "City", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
    @RequestWrapper(localName = "getCityByCountry", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/city", className = "edu.sjsu.voidstar.ws.soap.city.GetCityByCountry")
    @ResponseWrapper(localName = "getCityByCountryResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/soap/city", className = "edu.sjsu.voidstar.ws.soap.city.GetCityByCountryResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/CityService/getCityByCountryRequest", output = "http://ws.voidstar.sjsu.edu/CityService/getCityByCountryResponse")
    public List<City> getCityByCountry(
        @WebParam(name = "Country", targetNamespace = "http://ws.voidstar.sjsu.edu/dao")
        Country country);

}
