
package us.opulo.p.soap.language;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import us.opulo.p.dao.Country;
import us.opulo.p.dao.Language;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LanguageService", targetNamespace = "http://p.opulo.us/soap/language")
@XmlSeeAlso({
    us.opulo.p.dao.ObjectFactory.class,
    us.opulo.p.soap.language.ObjectFactory.class
})
public interface LanguageService {


    /**
     * 
     * @return
     *     returns java.util.List<us.opulo.p.dao.Language>
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getAllLanguages", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetAllLanguages")
    @ResponseWrapper(localName = "getAllLanguagesResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetAllLanguagesResponse")
    @Action(input = "http://p.opulo.us/soap/language/LanguageService/getAllLanguagesRequest", output = "http://p.opulo.us/soap/language/LanguageService/getAllLanguagesResponse")
    public List<Language> getAllLanguages();

    /**
     * 
     * @param id
     * @return
     *     returns us.opulo.p.dao.Language
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getLanguageWithId", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguageWithId")
    @ResponseWrapper(localName = "getLanguageWithIdResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguageWithIdResponse")
    @Action(input = "http://p.opulo.us/soap/language/LanguageService/getLanguageWithIdRequest", output = "http://p.opulo.us/soap/language/LanguageService/getLanguageWithIdResponse")
    public Language getLanguageWithId(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param ids
     * @return
     *     returns java.util.List<us.opulo.p.dao.Language>
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getLanguagesWithIds", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguagesWithIds")
    @ResponseWrapper(localName = "getLanguagesWithIdsResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguagesWithIdsResponse")
    @Action(input = "http://p.opulo.us/soap/language/LanguageService/getLanguagesWithIdsRequest", output = "http://p.opulo.us/soap/language/LanguageService/getLanguagesWithIdsResponse")
    public List<Language> getLanguagesWithIds(
        @WebParam(name = "ids", targetNamespace = "")
        List<Integer> ids);

    /**
     * 
     * @param name
     * @return
     *     returns us.opulo.p.dao.Language
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getLanguageWithName", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguageWithName")
    @ResponseWrapper(localName = "getLanguageWithNameResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguageWithNameResponse")
    @Action(input = "http://p.opulo.us/soap/language/LanguageService/getLanguageWithNameRequest", output = "http://p.opulo.us/soap/language/LanguageService/getLanguageWithNameResponse")
    public Language getLanguageWithName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param names
     * @return
     *     returns java.util.List<us.opulo.p.dao.Language>
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getLanguagesWithNames", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguagesWithNames")
    @ResponseWrapper(localName = "getLanguagesWithNamesResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguagesWithNamesResponse")
    @Action(input = "http://p.opulo.us/soap/language/LanguageService/getLanguagesWithNamesRequest", output = "http://p.opulo.us/soap/language/LanguageService/getLanguagesWithNamesResponse")
    public List<Language> getLanguagesWithNames(
        @WebParam(name = "names", targetNamespace = "")
        List<String> names);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<us.opulo.p.dao.Language>
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getLanguagesInCountry", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguagesInCountry")
    @ResponseWrapper(localName = "getLanguagesInCountryResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguagesInCountryResponse")
    @Action(input = "http://p.opulo.us/soap/language/LanguageService/getLanguagesInCountryRequest", output = "http://p.opulo.us/soap/language/LanguageService/getLanguagesInCountryResponse")
    public List<Language> getLanguagesInCountry(
        @WebParam(name = "Country", targetNamespace = "http://p.opulo.us/dao")
        Country country);

    /**
     * 
     * @param country
     * @return
     *     returns java.util.List<us.opulo.p.dao.Language>
     */
    @WebMethod
    @WebResult(name = "Language", targetNamespace = "http://p.opulo.us/dao")
    @RequestWrapper(localName = "getLanguagesInCountries", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguagesInCountries")
    @ResponseWrapper(localName = "getLanguagesInCountriesResponse", targetNamespace = "http://p.opulo.us/soap/language", className = "us.opulo.p.soap.language.GetLanguagesInCountriesResponse")
    @Action(input = "http://p.opulo.us/soap/language/LanguageService/getLanguagesInCountriesRequest", output = "http://p.opulo.us/soap/language/LanguageService/getLanguagesInCountriesResponse")
    public List<Language> getLanguagesInCountries(
        @WebParam(name = "Country", targetNamespace = "http://p.opulo.us/dao")
        List<Country> country);

}
