
package edu.sjsu.voidstar.ws.mashup;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MashupService", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MashupService {


    /**
     * 
     * @param languageName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountriesWhichSpeakLanguage", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetCountriesWhichSpeakLanguage")
    @ResponseWrapper(localName = "getCountriesWhichSpeakLanguageResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetCountriesWhichSpeakLanguageResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getCountriesWhichSpeakLanguageRequest", output = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getCountriesWhichSpeakLanguageResponse")
    public String getCountriesWhichSpeakLanguage(
        @WebParam(name = "languageName", targetNamespace = "")
        String languageName);

    /**
     * 
     * @param countryCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLanguagesSpokenInCountry", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetLanguagesSpokenInCountry")
    @ResponseWrapper(localName = "getLanguagesSpokenInCountryResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetLanguagesSpokenInCountryResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getLanguagesSpokenInCountryRequest", output = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getLanguagesSpokenInCountryResponse")
    public String getLanguagesSpokenInCountry(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getZombiesOnContinent", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetZombiesOnContinent")
    @ResponseWrapper(localName = "getZombiesOnContinentResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetZombiesOnContinentResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getZombiesOnContinentRequest", output = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getZombiesOnContinentResponse")
    public String getZombiesOnContinent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getZombiesBasedOnGeoIPLookup", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetZombiesBasedOnGeoIPLookup")
    @ResponseWrapper(localName = "getZombiesBasedOnGeoIPLookupResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetZombiesBasedOnGeoIPLookupResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getZombiesBasedOnGeoIPLookupRequest", output = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getZombiesBasedOnGeoIPLookupResponse")
    public String getZombiesBasedOnGeoIPLookup();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
<<<<<<< HEAD:mashup/src/main/java/edu/sjsu/voidstar/ws/mashup/MashupService.java
    @RequestWrapper(localName = "getCitiesWithTheMostZombies", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetCitiesWithTheMostZombies")
    @ResponseWrapper(localName = "getCitiesWithTheMostZombiesResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetCitiesWithTheMostZombiesResponse")
    public List<String> getCitiesWithTheMostZombies(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);
=======
    @RequestWrapper(localName = "testCountryLanguageMethods", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.TestCountryLanguageMethods")
    @ResponseWrapper(localName = "testCountryLanguageMethodsResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.TestCountryLanguageMethodsResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/MashupService/testCountryLanguageMethodsRequest", output = "http://ws.voidstar.sjsu.edu/mashup/MashupService/testCountryLanguageMethodsResponse")
    public String testCountryLanguageMethods();
>>>>>>> 4c62dd95907c517e9a9f81e38fe398c1374c0963:client/src/main/java/edu/sjsu/voidstar/ws/mashup/MashupService.java

    /**
     * 
     * @param cityName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getZombiesInCity", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetZombiesInCity")
    @ResponseWrapper(localName = "getZombiesInCityResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetZombiesInCityResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getZombiesInCityRequest", output = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getZombiesInCityResponse")
    public String getZombiesInCity(
        @WebParam(name = "cityName", targetNamespace = "")
        String cityName);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testCityMethods", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.TestCityMethods")
    @ResponseWrapper(localName = "testCityMethodsResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.TestCityMethodsResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/MashupService/testCityMethodsRequest", output = "http://ws.voidstar.sjsu.edu/mashup/MashupService/testCityMethodsResponse")
    public String testCityMethods();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testCountryMethods", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.TestCountryMethods")
    @ResponseWrapper(localName = "testCountryMethodsResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.TestCountryMethodsResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/MashupService/testCountryMethodsRequest", output = "http://ws.voidstar.sjsu.edu/mashup/MashupService/testCountryMethodsResponse")
    public String testCountryMethods();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testInfectionMethods", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.TestInfectionMethods")
    @ResponseWrapper(localName = "testInfectionMethodsResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.TestInfectionMethodsResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/MashupService/testInfectionMethodsRequest", output = "http://ws.voidstar.sjsu.edu/mashup/MashupService/testInfectionMethodsResponse")
    public String testInfectionMethods();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testLanguageMethods", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.TestLanguageMethods")
    @ResponseWrapper(localName = "testLanguageMethodsResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.TestLanguageMethodsResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/MashupService/testLanguageMethodsRequest", output = "http://ws.voidstar.sjsu.edu/mashup/MashupService/testLanguageMethodsResponse")
    public String testLanguageMethods();

    /**
     * 
     * @param languageName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getZombiesInCountriesWhereLanguageIsSpoken", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetZombiesInCountriesWhereLanguageIsSpoken")
    @ResponseWrapper(localName = "getZombiesInCountriesWhereLanguageIsSpokenResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetZombiesInCountriesWhereLanguageIsSpokenResponse")
    @Action(input = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getZombiesInCountriesWhereLanguageIsSpokenRequest", output = "http://ws.voidstar.sjsu.edu/mashup/MashupService/getZombiesInCountriesWhereLanguageIsSpokenResponse")
    public String getZombiesInCountriesWhereLanguageIsSpoken(
        @WebParam(name = "languageName", targetNamespace = "")
        String languageName);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountriesWithTheMostZombies", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetCountriesWithTheMostZombies")
    @ResponseWrapper(localName = "getCountriesWithTheMostZombiesResponse", targetNamespace = "http://ws.voidstar.sjsu.edu/mashup", className = "edu.sjsu.voidstar.ws.mashup.GetCountriesWithTheMostZombiesResponse")
    public List<String> getCountriesWithTheMostZombies(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
